import { router} from "./services/routeurService.js";
import { HomeRoute } from "./routes/HomeRoute.js";
import { LoginRoute } from "./routes/LoginRoute.js";
import { SignupRoute } from "./routes/SignupRoute.js";
import { SettingsRoute } from "./routes/SettingsRoute.js";
import { DashboardRoute } from "./routes/DashboardRoute.js";
import { Select2FAMethodRoute } from "./routes/Select2FAMethodRoute.js";
import { Setup2FAEmailRoute } from "./routes/Setup2FAEmailRoute.js";
import { Setup2FAQrCodeRoute } from "./routes/Setup2FAQrCodeRoute.js";
import { Disable2FAQrCodeRoute } from "./routes/Disable2FAQrCodeRoute.js";
import { Disable2FAEmailRoute } from "./routes/Disable2FAEmailRoute.js";

router.addRoute('home', new HomeRoute());
router.addRoute('login', new LoginRoute());
router.addRoute('signup', new SignupRoute());
router.addRoute('settings', new SettingsRoute());
router.addRoute('dashboard', new DashboardRoute());
router.addRoute('select-2fa-method', new Select2FAMethodRoute());
router.addRoute('setup-2fa-email', new Setup2FAEmailRoute());
router.addRoute('setup-2fa-qrcode', new Setup2FAQrCodeRoute());
router.addRoute('disable-2fa-qrcode', new Disable2FAQrCodeRoute());
router.addRoute('disable-2fa-email', new Disable2FAEmailRoute());
router.setup(document.getElementById('app')!);
await router.start();
