version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    networks:
      - transcendence
    command: sh -c "npm install && npm run dev"
  backend:
    image: node:alpine3.20
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "npm install && npm install -g nodemon && npm install sqlite3 &&npm start"
    networks:
      - transcendence
  nginx:
    build:
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - transcendence
networks:
  transcendence:
